Name:           ros-jade-web-video-server
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS web_video_server package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/web_video_server
Source0:        %{name}-%{version}.tar.gz

Requires:       ffmpeg-devel
Requires:       ros-jade-async-web-server-cpp
Requires:       ros-jade-cv-bridge
Requires:       ros-jade-image-transport
Requires:       ros-jade-roscpp
Requires:       ros-jade-roslib
BuildRequires:  ffmpeg-devel
BuildRequires:  ros-jade-async-web-server-cpp
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cv-bridge
BuildRequires:  ros-jade-image-transport
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-roslib

%description
HTTP Streaming of ROS Image Topics in Multiple Formats

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Apr 07 2015 Russell Toris <rctoris@wpi.edu> - 0.0.2-0
- Autogenerated by Bloom

